FROM node
RUN mkdir -p /usr/src/app
# RUN npm install @angular/material@6 @angular/cdk@6
WORKDIR /usr/src/app
COPY . /usr/src/app
# RUN npm install
# RUN npm install @angular/material@6 @angular/cdk@6
# RUN npm install -g nodemon
# RUN npm install chart.js --save
# RUN ng serve --host 0.0.0.0 --disableHostCheck
# CMD [ "npm", "start"]
# CMD [ "start"]
